'use client';
import './globals.css'
import Navbar from "../components/Navbar"
import { SessionProvider } from "next-auth/react";
import { CartProvider } from "use-shopping-cart";

export default function RootLayout({ children }) {
  return (
   <>
    <html lang="en">
      <title>Benna</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          precedence="default"
        />
        <link rel="icon" href="favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          precedence="default"
        />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=BioRhyme+Expanded&family=Delicious+Handrawn&family=Klee+One&family=Sue+Ellen+Francisco&family=Waterfall&display=swap&family=Amatic+SC&family=BioRhyme+Expanded" rel="stylesheet" />
      </head>
      <body>
        <CartProvider
          shouldPersist={true}
        >
          <SessionProvider>
            <Navbar />
            {children}
          </SessionProvider>
        </CartProvider>
      </body>
    </html>
    </> 
  )
}
